### ISSUE TITLE
download_file returns loaded json object not raw json

### ISSUE THREAD

**Issue by bartreardon** [joncrain/swiftDialog-scripts#1]
when downloading a json file here

https://github.com/joncrain/swiftDialog-scripts/blob/e6bb36e04866e667f94817ac931ee50eaec74d65/nudge-swiftdialog/payload/Library/CPE/bin/nudge#L61

the call to download_file expects raw json data to be returned but instead returns a loaded json object.

https://github.com/joncrain/swiftDialog-scripts/blob/e6bb36e04866e667f94817ac931ee50eaec74d65/nudge-swiftdialog/payload/Library/CPE/bin/nudge#L111

Either the call should expect a loaded object and thus `json.loads` should not be used or `download_file()` should return raw json. As it currently is, the script will not process the remote file

in my own implementation I amended `download_file()` to `return json_raw` and this works fine.

**Comment by joncrain** [comment]
Thanks.
This was a last minute copy/paste of that function before posting. To keep it consistent with the umad script, I went ahead and changed the remote file to process the loaded json.

https://github.com/joncrain/swiftDialog-scripts/blob/main/nudge-swiftdialog/payload/Library/CPE/bin/nudge#L61
